version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    # Uncomment if you want to connect to a backend service
    # depends_on:
    #   - backend
    # networks:
    #   - app-network

# Uncomment if you have a backend service
# services:
#   backend:
#     image: your-backend-image:latest
#     ports:
#       - "8080:8080"
#     environment:
#       - SPRING_PROFILES_ACTIVE=prod
#       - OPENAI_API_KEY=${OPENAI_API_KEY}
#     restart: unless-stopped
#     networks:
#       - app-network

# networks:
#   app-network:
#     driver: bridge 